# Generated by Django 6.0.1 on 2026-01-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploadDate', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'LOW'), (2, 'Medium'), (3, 'High')], null=True)),
            ],
        ),
    ]
